---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

# ansible.builtin.apt_key module failed while running on Ubuntu Server 25.04.
# Had to replace it with manual GPG key setup without apt-key as below 3 tasks
- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download docker GPG key and dearmor
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Set keyring permissions
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

# plucky (25.04) is not supported yet. Using 'noble' instead of ansible_lsb.codename
- name: Add Docker APT Repository
  apt_repository:
    repo: >
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu noble stable
    state: present
    filename: docker

- name: Update apt cache again
  apt:
    update_cache: yes

- name: Install docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

# For the user's group update to take effect, we need a logout/login.
# Elevate the test task to run as root.
- name: Test hello-world container
  become: true
  docker_container:
    name: hello-world
    image: hello-world
    auto_remove: yes
    state: started
